### PR TITLE
Merge migration flows functionality

### PR DESCRIPTION
**Pull request by walkerke**
@mfherman - opening this PR as I've been doing some testing and everything you've done seems very functional.  You mentioned a couple tweaks you wanted to make - what were you thinking about here?

### CODE REVIEW

**Comment by mfherman** [comment]
I just pushed a commit that changes the language from CBSA to MSA -- in looking closer at the docs, even though the geographic level to specify for the API is `metropolitan statistical area/micropolitan statistical area`, it only ever returns metros and so I thought MSA might be better here?

The main thing is that in 2015 and earlier, you can get the flows data crossed by certain demographic variables. 

https://api.census.gov/data/2015/acs/flows?get=SEX,RACE,MOVEDIN,GEOID1,GEOID2,MOVEDOUT,FULL1_NAME,FULL2_NAME,MOVEDNET&for=county:001&in=state:06

Currently that request will fail when `output = "tidy"`  because of the way the pivoting logic is working (`output = "wide"` works right now). 

```
get_flows(
   geography = "county",
   state = "06",
   county = "001",
   variables = c("SEX"),
   year = 2015,
   output = "tidy"
   )
Error: Problem with `mutate()` input `moe`.
x non-numeric argument to binary operator
i Input `moe` is `.data$moe * moe_factor`.
Run `rlang::last_error()` to see where the error occurred.
```

I should be able to fix that by telling `pivot_longer()` to not pivot the demographic vars. 

The only other thing is adding some more documentation. Maybe I can just add a couple of sections to the [Other datasets](https://walker-data.com/tidycensus/articles/other-datasets.html)?

In any case, I don't think either of things are huge issue for now, so feel free to merge into master and I can work on these over the next week or two as I have time.

**Comment by mfherman** [comment]
```
get_flows(
  geography = "county",
  state = "06",
   county = "001",
   variables = c("SEX", "AGE", "RACE"),
   year = 2015,
   output = "tidy"
   )
# A tibble: 61,974 x 10
   GEOID1 GEOID2 FULL1_NAME                 FULL2_NAME      SEX   AGE   RACE  variable estimate   moe
   <chr>  <chr>  <chr>                      <chr>           <chr> <chr> <chr> <chr>       <dbl> <dbl>
 1 06001  NA     Alameda County, California Africa          0     0     0     MOVEDIN       861   256
 2 06001  NA     Alameda County, California Africa          0     0     0     MOVEDOUT       NA    NA
 3 06001  NA     Alameda County, California Africa          0     0     0     MOVEDNET       NA    NA
 4 06001  NA     Alameda County, California Asia            0     0     0     MOVEDIN     11072  1106
 5 06001  NA     Alameda County, California Asia            0     0     0     MOVEDOUT       NA    NA
 6 06001  NA     Alameda County, California Asia            0     0     0     MOVEDNET       NA    NA
 7 06001  NA     Alameda County, California Central America 0     0     0     MOVEDIN      1733   343
 8 06001  NA     Alameda County, California Central America 0     0     0     MOVEDOUT       NA    NA
 9 06001  NA     Alameda County, California Central America 0     0     0     MOVEDNET       NA    NA
10 06001  NA     Alameda County, California Caribbean       0     0     0     MOVEDIN        18    19
```
Okay, was easy to take care of the issue of the demographic variables causing the error! I wouldn't mind building a little logic in to recode those characteristic variables so you don't have to go back and forth to the docs to check what the values mean:

https://www.census.gov/data/developers/data-sets/acs-migration-flows.2015.html

**Comment by walkerke** [comment]
@mfherman looks great!  A couple thoughts to discuss - 

- I agree with the automatic recoding functionality.  We have this available in `get_estimates()` where the recoded labels replace the data values directly, and then of course as separate columns with respect to the PUMS data. 
- Also, this use case is very similar to the `breakdown` parameter in `get_estimates()` as `SEX`, `AGE`, etc. are not variables _per se_ (as they don't end up in the `variables` column) but rather characteristics of the flows data.  For example, in `get_estimates()` we do this: 

```r
get_estimates(
  geography = "county",
  product = "characteristics",
  breakdown = c("SEX", "AGEGROUP"),
  breakdown_labels = TRUE,
  state = "TX"
)
```

```
# A tibble: 24,384 x 5
   GEOID NAME               value SEX        AGEGROUP          
   <chr> <chr>              <dbl> <chr>      <fct>             
 1 48373 Polk County, Texas 51353 Both sexes All ages          
 2 48373 Polk County, Texas  2701 Both sexes Age 0 to 4 years  
 3 48373 Polk County, Texas  2824 Both sexes Age 5 to 9 years  
 4 48373 Polk County, Texas  3022 Both sexes Age 10 to 14 years
 5 48373 Polk County, Texas  2646 Both sexes Age 15 to 19 years
 6 48373 Polk County, Texas  2799 Both sexes Age 20 to 24 years
 7 48373 Polk County, Texas  3152 Both sexes Age 25 to 29 years
 8 48373 Polk County, Texas  3091 Both sexes Age 30 to 34 years
 9 48373 Polk County, Texas  3168 Both sexes Age 35 to 39 years
10 48373 Polk County, Texas  2936 Both sexes Age 40 to 44 years
# … with 24,374 more rows
```

What would you think about a similar implementation to this - separate arguments for the nominal characteristics of the flows data and the flows variables themselves?  

- Regarding documentation, I think a small section in "Other datasets" makes a lot of sense.  [Indeed, this was the plan several years ago before I abandoned the idea!](https://github.com/walkerke/tidycensus/blob/e350c4b5ca8aae6a24a29f82020ff4c233bd8aba/vignettes/other-datasets.Rmd#L126)

**Comment by mfherman** [comment]
Oh yes, it is very similar to the `get_estimates()` recoding. I’ll take a look at your implementation there and mirror it. I think it makes sense to separate the variables from the characteristics in the call, so I’ll also make that consistent with the arguments to `get_estimates()`.

I should have time in the next few days to implement that and write up a couple examples for the vignette. I’ll ping you when I’ve pushed those commits!

**Comment by mfherman** [comment]
Alright, I think the recoding is working! Somewhat surprisingly, this wrangling took longer that a lot of the other features in `get_flows()`. I opted to reuse the logic from `get_pums()` for recoding from a built in dataset -- since there are a number of characteristics available over the different years, it seemed a better approach than manually recoding each variable. It should also create ordered factors for appropriate variables such as age and income. Let me know if you have thoughts about this implementation

```r
get_flows(
  geography = "county",
  breakdown = "AHINC",
  breakdown_labels = TRUE,
  state = "NJ",
  county = "Bergen",
  year = 2011
)
Using FIPS code '34' for state 'NJ'
Using FIPS code '003' for 'Bergen County'
# A tibble: 10,305 x 9
   GEOID1 GEOID2 FULL1_NAME                FULL2_NAME      AHINC AHINC_label       variable estimate   moe
   <chr>  <chr>  <chr>                     <chr>           <chr> <ord>             <chr>       <dbl> <dbl>
 1 34003  NA     Bergen County, New Jersey Africa          00    All income levels MOVEDIN       373   199
 2 34003  NA     Bergen County, New Jersey Africa          00    All income levels MOVEDOUT       NA    NA
 3 34003  NA     Bergen County, New Jersey Africa          00    All income levels MOVEDNET       NA    NA
 4 34003  NA     Bergen County, New Jersey Asia            00    All income levels MOVEDIN      4222   721
 5 34003  NA     Bergen County, New Jersey Asia            00    All income levels MOVEDOUT       NA    NA
 6 34003  NA     Bergen County, New Jersey Asia            00    All income levels MOVEDNET       NA    NA
 7 34003  NA     Bergen County, New Jersey Central America 00    All income levels MOVEDIN       282   341
 8 34003  NA     Bergen County, New Jersey Central America 00    All income levels MOVEDOUT       NA    NA
 9 34003  NA     Bergen County, New Jersey Central America 00    All income levels MOVEDNET       NA    NA
10 34003  NA     Bergen County, New Jersey Caribbean       00    All income levels MOVEDIN       375   154
# ... with 10,295 more rows
```

So then the only thing left for now is a couple examples to add to the vignette, which I should be able to get to in the next couple days. Thanks for the push forward on this!

**Comment by walkerke** [comment]
@mfherman amazing stuff!!!  I'm really impressed by how you pulled this together so quickly.  I'm going to merge this into the master branch.  

With all the new features I'd like to move this to 1.0 when we publish to CRAN; I was waiting for the restoration of the 1990 API endpoint to do this but I don't think there is a timeline for that anymore.

**Comment by mfherman** [comment]
Excellent! It definitely came together more quickly than the `get_cps()` work, though I would like to get back to that at some point. I'm still sort of stuck on the idea of creating a hex logo for 1.0, but I'm such a terrible graphic designer that I'm not sure what I can do. I did have this idea of putting somethink like the [weepeople glyphs](https://github.com/propublica/weepeople) in a grid, and threw this together real quick. I'm sure someone with good skills could do something good with this, but not sure it's me!

image

**Comment by walkerke** [comment]
yep I'd like a hex logo too.  I've had a couple ideas... I was able to fumble around and make a sticker for tigris so I'll open up an issue and tweet it out for suggestions, maybe a user has an idea too!

**Pull request merged**
