### PR TITLE
Recode orderedfactors

### PR DESCRIPTION
**Pull request by szimmer**
This is a proposed solution to issue #273. 

This also fixes an issue where if multiple states are specified in `get_pums` that a condition is no longer of length > 1 when checking that "all" states are specified.

### CODE REVIEW

**Comment by walkerke** [comment]
Thank you!  I'll go through this today.

**Comment by walkerke** [comment]
@szimmer @mfherman -

I like this PR quite a lot and I think it should eventually be merged.  Right now it is breaking a couple examples in the PUMS vignette, specifically https://github.com/walkerke/tidycensus/blob/master/vignettes/pums-data.Rmd#L164-L165 and https://github.com/walkerke/tidycensus/blob/master/vignettes/pums-data.Rmd#L179-L187.  Reproducibly, I get: 

```r
library(tidycensus)
library(tidyverse)
library(srvyr)

vt_survey_design <- get_pums(
  variables = c("PUMA", "SEX", "AGEP", "SCHL"),
  state = "VT",
  survey = "acs1",
  recode = TRUE,
  rep_weights = "person"
  ) %>%
to_survey()

vt_survey_design %>% 
  survey_count(PUMA, SEX_label)

Error: Can't join on `x$SEX_label` x `y$SEX_label` because of incompatible types.
ℹ `x$SEX_label` is of type <ordered<7fae0>>>.
ℹ `y$SEX_label` is of type <factor<7fae0>>>.
```

I _think_ something is going on internally in {srvyr} that coerces our ordered factor to a regular factor and then tries to do a join as part of the survey-weighted calculation, which fails.  I haven't yet tracked this down.  I think there are a couple options then: 

1) Specify the labels as regular factors with correctly ordered levels, which I haven't tested but I think should work; 
2) Identify the issue in srvyr and submit a PR, then merge afterward.  

I'm personally partial to option 2 - copying @gergness here as well in case you have any feedback/ideas, Greg.

**Comment by szimmer** [comment]
I see. This is an issue with srvyr. Smaller reproducible example with data from the `survey` package. I suppose the factor doesn't need to be ordered but the levels need the right order to show the difference between stype and stype_factor below. Elementary then Middle then High School in summaries and plots.

``` r
library(tidyverse)
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart
library(srvyr)
#> 
#> Attaching package: 'srvyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter


data(api)

apisrs_mut <- apisrs %>%
  as_tibble() %>%
  mutate(stype_factor=parse_factor(as.character(stype), levels=c("E", "M", "H")),
         stype_ordered_factor=parse_factor(as.character(stype), levels=c("E", "M", "H"), ordered = TRUE))

apisrs_mut %>% select(starts_with("stype")) %>% summary()
#>  stype   stype_factor stype_ordered_factor
#>  E:142   E:142        E:142               
#>  H: 25   M: 33        M: 33               
#>  M: 33   H: 25        H: 25

srs_design_srvyr  <- apisrs_mut %>%
  as_survey_design(ids = 1, fpc = fpc)

srs_design_srvyr %>%
  survey_count(stype)
#> Warning: The `add` argument of `group_by()` is deprecated as of dplyr 1.0.0.
#> Please use the `.add` argument instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> # A tibble: 3 x 3
#>   stype     n  n_se
#>   <fct> <dbl> <dbl>
#> 1 E     4398.  196.
#> 2 H      774.  143.
#> 3 M     1022.  160.

srs_design_srvyr %>%
  survey_count(stype_factor)
#> # A tibble: 3 x 3
#>   stype_factor     n  n_se
#>   <fct>        <dbl> <dbl>
#> 1 E            4398.  196.
#> 2 M            1022.  160.
#> 3 H             774.  143.

srs_design_srvyr %>%
  survey_count(stype_ordered_factor)
#> Error: Can't join on `x$stype_ordered_factor` x `y$stype_ordered_factor` because of incompatible types.
#> i `x$stype_ordered_factor` is of type <ordered<90f33>>>.
#> i `y$stype_ordered_factor` is of type <factor<90f33>>>.



# Demonstrate order in plotting

out <- apisrs_mut %>%
  mutate(hs_grad_pct = cut(hsg, c(0, 20, 100), include.lowest = TRUE,
                           labels = c("<20%", "20+%"))) %>%
  group_by(stype, stype_factor, stype_ordered_factor, hs_grad_pct) %>%
  summarize(api_diff = weighted.mean(api00 - api99, pw),
            n = n())
#> `summarise()` regrouping output by 'stype', 'stype_factor', 'stype_ordered_factor' (override with `.groups` argument)

ggplot(data = out, aes(x = stype, y = api_diff, group = hs_grad_pct, fill = hs_grad_pct)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(y = 0, label = n), position = position_dodge(width = 0.9), vjust = -1)
```



``` r

ggplot(data = out, aes(x = stype_factor, y = api_diff, group = hs_grad_pct, fill = hs_grad_pct)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(y = 0, label = n), position = position_dodge(width = 0.9), vjust = -1)
```



``` r

ggplot(data = out, aes(x = stype_ordered_factor, y = api_diff, group = hs_grad_pct, fill = hs_grad_pct)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(y = 0, label = n), position = position_dodge(width = 0.9), vjust = -1)
```



<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gergness** [comment]
Indeed a bug in srvyr, thanks for the good reprex!

**Comment by gergness** [comment]
fix in srvyr is on CRAN now

**Comment by walkerke** [comment]
Thank you @gergness!  @szimmer - I'll re-run your PR to check it and merge shortly assuming all checks out.

**Comment by walkerke** [comment]
Tested and working now.  Thanks @szimmer!

**Pull request merged**
